### ISSUE TITLE
AttributeError: module 'data_dif' has no attribute 'show_prnu_fft'

### ISSUE THREAD

**Issue by goen-kkk** [Sergo2020/DIF_pytorch_official#1]
Traceback (most recent call last):
  File "blank_experiment.py", line 78, in <module>
    preform_blank(parse_arguments())
  File "blank_experiment.py", line 69, in preform_blank
    fin_fft = data.show_prnu_fft(fin_list[ep], r'$\hat{Y}$' + f' {ep}')
AttributeError: module 'data_dif' has no attribute 'show_prnu_fft'

**Comment by Sergo2020** [comment]
produce_fft is added to data_dif and the call for show_prnu_fft is removed
