### ISSUE TITLE
Will the dataset be available?

### ISSUE THREAD

**Issue by TianyunYoung** [Sergo2020/DIF_pytorch_official#2]
I appreciate your interesting findings in this paper. I am also doing some research about model fingerprints. Could you share the dataset including dalle_2, dalle_mini, glide, mj, sd14, and sd21? Thanks a lot!

**Comment by Sergo2020** [comment]
Hi, thank you for the interest in the work.
I'm planning to upload the data, but it will take some time.

Currently, I suggest you to check out repository of the similar work "On the detection of synthetic images generated by diffusion models". They uploaded similar dataset. In addition, full MJ dataset, from which sub set was taken, is available on kaggle (link in the DIF paper).

**Comment by TianyunYoung** [comment]
I got it. Thanks for your help.
